conda activate general

sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode01.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode01
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode02.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode02
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode03.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode03
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode04.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode04
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode05.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode05
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode06.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode06
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode07.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode07
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode08.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode08
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode09.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode09
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode10.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode10
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode11.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode11
sh GitHub/General/align_Nanopore_sequencing_raw_reads_without_splicing.sh GitHub/replace_UG_in_first_800_bp_of_ELK1_extended_3_prime_UTR/9_analyse\ results\ from\ minION\ with\ Flow\ Cell\ \(R10.4.1\)/reference.fasta /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/combined_barcode12.fastq.gz /Volumes/lab-frattap/home/users/jeanz/Nanopore_sequencing/ELK1_UG_replaced_library_in_Dox_curve/barcode12